---
title: "Untitled"
author: "eipi10"
date: "11/19/2016"
output:
  pdf_document:
    fig_caption: yes
    includes:
      in_header: header.tex
  word_document: default
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, message=FALSE)
library(xtable)
```

```{r}
x <- structure(c(3, 6, 9, 35,2,4,5,6,1,2,3,1,3, 6, 9, 35,2,4,5,6,1,2,3,1),.Dim = c(4, 6), .Dimnames = structure(list(Actual = c("EU-19", "Deutschland","A","B"), Predicted = c("A", "B","A","B","A","B")), .Names = c("Actual", "Predicted")), class = "table")
xl <- list(x)
attr(xl, "message") <- c("A caption", "Which can have multiple lines")


PrintConfusionMatrix <- function(data, ...) {

  stopifnot(all(dim(x) == c(4, 6)))

#  colnames(x) <- sprintf("\\emph{%s}", colnames(x)) # highlight colnames
#  rownames(x) <- sprintf("\\emph{%s}", rownames(x)) # highlight rownames

  cat('\\begin{tabular}{|c *{8}{|C{2cm}}|} \\cline{2-7}
    \\multicolumn{1}{c|}{} & \\multicolumn{6}{c|}{\\textbf{$\\Delta$ Einschätzungen}} \\\\ \\cline{2-7}
    \\multicolumn{1}{c|}{} & \\multicolumn{2}{c|}{\\textbf{Wirtsch. Lage}} & \\multicolumn{2}{c|}{\\textbf{Ind.\nVertrauensind.}} & \\multicolumn{2}{c|}{\\textbf{DL\n Vertrauensind.}} \\\\ \\hline
    \\textbf{Land} ')


print(xtable(x,caption="Hallo"),
        only.contents = TRUE, 
        comment = FALSE,
        sanitize.colnames.function = identity, 
        sanitize.rownames.function = identity, 
        hline.after = 0:4,
        ...)
  cat("\\end{tabular}")


}
```

```{r, results='asis'}

PrintConfusionMatrix(x)

```
Table: Hsfasfiwe
